---
# deploy-container.yml
- name: Deploy Java Application Docker Container
  hosts: app_servers
  become: no
  vars:
    image_repo: "{{ image_repo }}"
    image_name: "{{ image_name }}"
    app_port: "{{ app_port }}"
    container_port: "{{ container_port }}"
    app_dir: "{{ playbook_dir }}"  # Use the directory where the playbook is located
    
  tasks:
    - name: Stop and remove containers using the same port
      shell: |
        # Find and stop containers using the same port
        for container_id in $(docker ps -q --filter "publish={{ app_port }}"); do
          docker stop $container_id
          docker rm $container_id
        done
      ignore_errors: yes
    
    - name: Build Docker image
      command: docker build -t {{ image_repo }}:{{ image_name }} {{ app_dir }}
      args:
        chdir: "{{ app_dir }}"
    
    - name: Run Docker container
      command: >
        docker run -d 
        --name {{ image_repo | basename }}-{{ image_name }} 
        -p {{ app_port }}:{{ container_port }} 
        --restart always 
        {{ image_repo }}:{{ image_name }}
      
 
